# Kindly note , if the cc in the youtube video is autogenerated then it will not be downloaded , check the sample video link added for mmore details.
import yt_dlp as youtube_dl

ydl_opts = {
    'writesubtitles': True,  # Downloads subtitles
    'skip_download': True,   # Skips downloading the video
    #'subtitleslangs': ['en'],    # Request English subtitles
}

video_url = "https://www.youtube.com/watch?v=lv1_-RER4_I"

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([video_url])